dist: xenial
addons:
  chrome: stable
language: node_js
install:
  - npm ci
  - npm run webdriver:update
cache:
  directories:
<<<<<<< HEAD
    - 'node_modules'
=======
    - "node_modules"
>>>>>>> 02efc2a (add the launch.json to make debug)
